name: Build into Github Pages Artefact.

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  CI: ""

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Git and Access Tokens
      run: |
        git remote set-url origin git@github.com:Suraj-Upadhyay/Algorithm-Visualiser.git
        /usr/bin/git config --global --add url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github".insteadOf ssh://git@github
        /usr/bin/git config --global --add url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github".insteadOf https://github
        /usr/bin/git config --global --add url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github".insteadOf git@github
        git remote set-url origin https://Suraj-Upadhyay:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/Suraj-Upadhyay/Algorithm-Visualiser.git
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run NPM install and build
      run: |
        npm ci
        npm run build
    - name: Publish artefacts to gh-pages branch
      run : |
        git --work-tree dist add --all
        git commit -m "Automatic Build and Deploy run by GitHub Actions"
        git push origin HEAD:gh-pages --force
      shell: bash
